services:
  postgres:
    image: postgres:15-alpine
    container_name: hafood_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: hafood_db
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: hafood_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: