package com.hafood.sistema.constant;

public enum AccionAuditoria {
    CUENTA_ABIERTA,
    LINEA_AGREGADA,
    LINEA_MODIFICADA,
    LINEA_ELIMINADA,
    CUENTA_ANULADA,
    MESA_CAMBIADA,
    MESA_AGREGADA,
    CUENTAS_UNIDAS,
    CUENTA_FUSIONADA,
    MOZO_CAMBIADO,
    DESCUENTO_APLICADO,
    CORTESIA_APLICADA,
    DESCUENTO_QUITADO,
    COMANDA_ENVIADA,
    LINEA_ESTADO_CAMBIADO
}